name: CI
on:
  push:
    branches:
      - master
      - sdk-5
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [14]
    name: CI on NodeJS v${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - run: yarn
      - run: yarn check-code
      - run: yarn build
      - uses: actions/upload-artifact@master
        with:
          name: build
          path: build
